# Generated by Django 6.0.2 on 2026-03-04 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroup',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', through='stress_app.GroupMembership', through_fields=('group', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
