# Generated by Django 6.0.2 on 2026-03-25 20:12

import django.core.validators
import stress_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress_app', '0002_supportgroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='source_url',
            field=models.URLField(blank=True, help_text='Ссылка на оригинальный источник материала', null=True, verbose_name='URL источника'),
        ),
        migrations.AddField(
            model_name='resource',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube или Vimeo видео', null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AddField(
            model_name='supportgroup',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Zoom, Google Meet или другая ссылка для онлайн встреч', null=True, verbose_name='Ссылка на встречу'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Иконка для категории (32x32 px)', null=True, upload_to='category_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию эксперта', null=True, upload_to=stress_app.models.expert_photo_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Изображение для обложки ресурса', null=True, upload_to='resource_covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='Загрузите файл ресурса (PDF, MP3, MP4 и т.д.)', null=True, upload_to=stress_app.models.resource_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'mp3', 'mp4', 'txt', 'doc', 'docx'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='group_image',
            field=models.ImageField(blank=True, help_text='Изображение для группы поддержки', null=True, upload_to='group_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для аватара (JPEG, PNG)', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
